-- 코드를 입력하세요
SELECT c.AUTHOR_ID, c.AUTHOR_NAME, a.CATEGORY, sum(SALES * PRICE) TOTAL_PRICE
FROM 
    BOOK as a LEFT JOIN 
        (SELECT *
        FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1) as b
    ON a.BOOK_ID = b.BOOK_ID
    JOIN AUTHOR as c
    ON a.AUTHOR_ID = c.AUTHOR_ID
GROUP BY c.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

# ORDER BY AUTHOR_ID, CATEGORY DESC