-- 코드를 작성해주세요
SELECT b.ITEM_ID, b.ITEM_NAME
FROM 
    (SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL) as a JOIN ITEM_INFO as b
    ON a.ITEM_ID = b.ITEM_ID
WHERE a.ITEM_ID = b.ITEM_ID
ORDER BY b.ITEM_ID