-- 코드를 입력하세요
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM 
    (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE) as b
    JOIN REST_INFO as a
    
WHERE a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.FAVORITES
ORDER BY a.FOOD_TYPE DESC