-- 코드를 입력하세요
SELECT a.USER_ID, a.NICKNAME, CONCAT(a.CITY, " ", a.STREET_ADDRESS1, " ", a.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(TLNO, 1, 3), "-",SUBSTRING(TLNO, 4, 4) ,"-", SUBSTRING(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER as a LEFT JOIN USED_GOODS_BOARD as b
ON a.USER_ID = b.WRITER_ID
GROUP BY (a.USER_ID)
HAVING COUNT(a.USER_ID) >= 3
ORDER BY a.USER_ID DESC