SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS,  ROUND(FORMAT(AVG(b.REVIEW_SCORE), 2), 2) SCORE

FROM REST_INFO as a join REST_REVIEW as b
    USING(REST_ID)
GROUP BY(REST_ID)
HAVING LEFT(ADDRESS, 2) = '서울'
ORDER BY SCORE DESC, a.FAVORITES DESC

