SELECT YEAR, MONTH, PUCHASED_USERS, 
    ROUND(PUCHASED_USERS / TOTAL_JOIN_COUNT, 1) AS PUCHASED_RATIO
FROM (SELECT COUNT(USER_ID) AS TOTAL_JOIN_COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021) AS A
CROSS JOIN
(SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT(USER_ID)) AS PUCHASED_USERS
FROM ONLINE_SALE AS C LEFT JOIN USER_INFO AS B USING (USER_ID)
WHERE YEAR(B.JOINED) = 2021
GROUP BY YEAR, MONTH) AS D
ORDER BY YEAR, MONTH