-- 코드를 입력하세요
SELECT b.PRODUCT_ID, b.PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_ORDER as a LEFT JOIN FOOD_PRODUCT as b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE b.PRODUCT_ID IS NOT NULL AND YEAR(a.PRODUCE_DATE) = 2022 AND MONTH(a.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID