-- 코드를 입력하세요
SELECT HISTORY_ID, 
    (CASE 
     WHEN DATE_DIF + 1 < 7 THEN ROUND(DAILY_FEE * (DATE_DIF + 1), 0)
     ELSE ROUND(DAILY_FEE * ((100 - DISCOUNT_RATE) / 100) * (DATE_DIF + 1), 0)
     END
    ) FEE
FROM (SELECT *
FROM CAR_RENTAL_COMPANY_CAR AS A 
JOIN  (SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE, TIMESTAMPDIFF(DAY, START_DATE, END_DATE) AS DATE_DIF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS B
USING (CAR_ID)
WHERE CAR_TYPE = '트럭') AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
USING (CAR_TYPE)
WHERE duration_type = '90일 이상' AND DATE_DIF + 1 >= 90 OR
duration_type = '30일 이상' AND DATE_DIF + 1 >= 30 AND DATE_DIF + 1 < 90 OR
duration_type = '7일 이상' AND DATE_DIF + 1 >= 7 AND DATE_DIF + 1 < 30 OR
DATE_DIF + 1 < 7 
GROUP BY (HISTORY_ID)
ORDER BY FEE DESC, HISTORY_ID DESC
