-- 코드를 입력하세요
WITH RECURSIVE RE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM RE
    WHERE HOUR < 23
)

SELECT b.HOUR AS HOUR, COUNT(a.DATETIME) AS COUNT
FROM RE as b
LEFT JOIN ANIMAL_OUTS as a
ON HOUR(a.DATETIME) = b.HOUR
GROUP BY b.HOUR;

