-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) TOTAL_SALES
FROM (SELECT * 
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE') as B 
    JOIN USED_GOODS_USER as U
    ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES