SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (SELECT MEMBER_ID
    FROM rest_review
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
        SELECT MAX(REVIEW_COUNT)
        FROM (
            SELECT COUNT(MEMBER_ID) AS REVIEW_COUNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS COUNTS
    )) AS B
LEFT JOIN REST_REVIEW  AS C
USING (MEMBER_ID)
JOIN MEMBER_PROFILE
USING (MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT