# SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
# FROM (SELECT ITEM_ID
#     FROM ITEM_INFO
#     WHERE RARITY = 'RARE') as a 
#     JOIN ITEM_TREE as b
#     ON a.ITEM_ID = b.PARENT_ITEM_ID
#     JOIN
#     ITEM_INFO as c
# WHERE b.ITEM_ID = c.ITEM_ID
# ORDER BY c.ITEM_ID DESC

SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_INFO AS c
INNER JOIN ITEM_TREE AS b ON b.ITEM_ID = c.ITEM_ID
INNER JOIN ITEM_INFO AS a ON a.ITEM_ID = b.PARENT_ITEM_ID
WHERE a.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;
