SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD as a join USED_GOODS_REPLY as b
    on a.BOARD_ID = b.BOARD_ID
WHERE YEAR(a.CREATED_DATE) = 2022 and MONTH(a.CREATED_DATE) = 10
ORDER BY b.CREATED_DATE ASC, a.TITLE ASC;