WITH RECURSIVE RE 
AS (
    SELECT 0 AS PRICE
    UNION ALL
    SELECT PRICE + 10000
    FROM RE
    WHERE PRICE < (SELECT FLOOR(MAX(PRICE) - 10000)
              FROM PRODUCT)
)
SELECT r.PRICE AS PRICE_GROUP, COUNT(*) PRODUCTS
FROM RE as r LEFT JOIN PRODUCT as p
ON FLOOR(p.price / 10000)*10000 = r.PRICE
GROUP BY r.PRICE
HAVING COUNT(p.PRODUCT_ID) > 0
ORDER BY PRICE_GROUP